/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserEntity } from '../../models/user-entity';

export interface ApiAuthWhoamiGet$Xml$Params {
}

export function apiAuthWhoamiGet$Xml(http: HttpClient, rootUrl: string, params?: ApiAuthWhoamiGet$Xml$Params, context?: HttpContext): Observable<StrictHttpResponse<UserEntity>> {
  const rb = new RequestBuilder(rootUrl, apiAuthWhoamiGet$Xml.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/xml', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserEntity>;
    })
  );
}

apiAuthWhoamiGet$Xml.PATH = '/api/Auth/whoami';
