/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkoutLog } from '../../models/workout-log';

export interface ApiScheduleExercisePost$Params {
  body: WorkoutLog;
}

export function apiScheduleExercisePost(http: HttpClient, rootUrl: string, params: ApiScheduleExercisePost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkoutLog>> {
  const rb = new RequestBuilder(rootUrl, apiScheduleExercisePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkoutLog>;
    })
  );
}

apiScheduleExercisePost.PATH = '/api/Schedule/exercise';
