/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MuscleGroup } from '../../models/muscle-group';

export interface ApiScheduleTodayMuscleGet$Params {
}

export function apiScheduleTodayMuscleGet(http: HttpClient, rootUrl: string, params?: ApiScheduleTodayMuscleGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MuscleGroup>>> {
  const rb = new RequestBuilder(rootUrl, apiScheduleTodayMuscleGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MuscleGroup>>;
    })
  );
}

apiScheduleTodayMuscleGet.PATH = '/api/Schedule/today/muscle';
