/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserEntity {
  email?: string | null;
  firstName?: string | null;
  id?: string;
  lastName?: string | null;
  oAuthId?: string | null;
}
