/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Equipment } from '../../models/equipment';

export interface ApiGymEquipmentGet$Params {
      body?: string
}

export function apiGymEquipmentGet(http: HttpClient, rootUrl: string, params?: ApiGymEquipmentGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Equipment>>> {
  const rb = new RequestBuilder(rootUrl, apiGymEquipmentGet.PATH, 'get');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Equipment>>;
    })
  );
}

apiGymEquipmentGet.PATH = '/api/Gym/equipment';
