/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Equipment } from './models/equipment';
export type { Gym } from './models/gym';
export type { User } from './models/user';
