/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiEntityGetentityGet } from '../fn/entity/api-entity-getentity-get';
import { ApiEntityGetentityGet$Params } from '../fn/entity/api-entity-getentity-get';

@Injectable({ providedIn: 'root' })
export class EntityService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiEntityGetentityGet()` */
  static readonly ApiEntityGetentityGetPath = '/api/Entity/getentity';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEntityGetentityGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEntityGetentityGet$Response(params?: ApiEntityGetentityGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEntityGetentityGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEntityGetentityGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEntityGetentityGet(params?: ApiEntityGetentityGet$Params, context?: HttpContext): Observable<void> {
    return this.apiEntityGetentityGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
