/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiGymGet } from '../fn/gym/api-gym-get';
import { ApiGymGet$Params } from '../fn/gym/api-gym-get';
import { Gym } from '../models/gym';

@Injectable({ providedIn: 'root' })
export class GymService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiGymGet()` */
  static readonly ApiGymGetPath = '/api/Gym';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGymGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGymGet$Response(params?: ApiGymGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Gym>>> {
    return apiGymGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGymGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGymGet(params?: ApiGymGet$Params, context?: HttpContext): Observable<Array<Gym>> {
    return this.apiGymGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Gym>>): Array<Gym> => r.body)
    );
  }

}
