/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Muscle } from '../models/muscle';
import { MuscleGroup } from '../models/muscle-group';
export interface Exercise {
  description?: string | null;
  icon?: string | null;
  id?: string;
  name?: string | null;
  primaryMuscle?: Muscle;
  primaryMuscleGroup?: MuscleGroup;
  secondaryMuscle?: Muscle;
  secondaryMuscleGroup?: MuscleGroup;
}
