/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum Muscle {
  Abs = 'Abs',
  Abductors = 'Abductors',
  Adductors = 'Adductors',
  Biceps = 'Biceps',
  Calves = 'Calves',
  Chest = 'Chest',
  Forearms = 'Forearms',
  Glutes = 'Glutes',
  Hamstrings = 'Hamstrings',
  Lats = 'Lats',
  LowerBack = 'LowerBack',
  MiddleBack = 'MiddleBack',
  Neck = 'Neck',
  Quadriceps = 'Quadriceps',
  Shoulders = 'Shoulders',
  Traps = 'Traps',
  Triceps = 'Triceps'
}
