/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimeSpan {
  days?: number;
  hours?: number;
  microseconds?: number;
  milliseconds?: number;
  minutes?: number;
  nanoseconds?: number;
  seconds?: number;
  ticks?: number;
  totalDays?: number;
  totalHours?: number;
  totalMicroseconds?: number;
  totalMilliseconds?: number;
  totalMinutes?: number;
  totalNanoseconds?: number;
  totalSeconds?: number;
}
