/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimeSpan } from '../models/time-span';
export interface WorkoutLog {
  date?: string;
  duration?: TimeSpan;
  exerciseId?: string;
  id?: string;
  reps?: number;
  scheduleId?: string;
  sets?: number;
  weight?: number;
}
