/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiExerciseGet } from '../fn/exercise/api-exercise-get';
import { ApiExerciseGet$Params } from '../fn/exercise/api-exercise-get';
import { Exercise } from '../models/exercise';

@Injectable({ providedIn: 'root' })
export class ExerciseService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiExerciseGet()` */
  static readonly ApiExerciseGetPath = '/api/Exercise';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiExerciseGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiExerciseGet$Response(params?: ApiExerciseGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Exercise>>> {
    return apiExerciseGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiExerciseGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiExerciseGet(params?: ApiExerciseGet$Params, context?: HttpContext): Observable<Array<Exercise>> {
    return this.apiExerciseGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Exercise>>): Array<Exercise> => r.body)
    );
  }
}