/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiScheduleMondayGet } from '../fn/schedule/api-schedule-monday-get';
import { ApiScheduleMondayGet$Params } from '../fn/schedule/api-schedule-monday-get';
import { apiSchedulePost } from '../fn/schedule/api-schedule-post';
import { ApiSchedulePost$Params } from '../fn/schedule/api-schedule-post';
import { apiScheduleTodayExerciseGet } from '../fn/schedule/api-schedule-today-exercise-get';
import { ApiScheduleTodayExerciseGet$Params } from '../fn/schedule/api-schedule-today-exercise-get';
import { apiScheduleTodayMuscleGet } from '../fn/schedule/api-schedule-today-muscle-get';
import { ApiScheduleTodayMuscleGet$Params } from '../fn/schedule/api-schedule-today-muscle-get';
import { apiScheduleExercisePost } from '../fn/schedule/api-schedule-exercise-post';
import { ApiScheduleExercisePost$Params } from '../fn/schedule/api-schedule-exercise-post';
import { WorkoutLog } from '../models/workout-log';
import { Exercise } from '../models/exercise';
import { MuscleGroup } from '../models/muscle-group';
import { WeeklySchedule } from '../models/weekly-schedule';

@Injectable({ providedIn: 'root' })
export class ScheduleService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiScheduleTodayMuscleGet()` */
  static readonly ApiScheduleTodayMuscleGetPath = '/api/Schedule/today/muscle';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiScheduleTodayMuscleGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiScheduleTodayMuscleGet$Response(params?: ApiScheduleTodayMuscleGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MuscleGroup>>> {
    return apiScheduleTodayMuscleGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiScheduleTodayMuscleGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiScheduleTodayMuscleGet(params?: ApiScheduleTodayMuscleGet$Params, context?: HttpContext): Observable<Array<MuscleGroup>> {
    return this.apiScheduleTodayMuscleGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MuscleGroup>>): Array<MuscleGroup> => r.body)
    );
  }

  /** Path part for operation `apiScheduleTodayExerciseGet()` */
  static readonly ApiScheduleTodayExerciseGetPath = '/api/Schedule/today/exercise';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiScheduleTodayExerciseGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiScheduleTodayExerciseGet$Response(params?: ApiScheduleTodayExerciseGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Exercise>>> {
    return apiScheduleTodayExerciseGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiScheduleTodayExerciseGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiScheduleTodayExerciseGet(params?: ApiScheduleTodayExerciseGet$Params, context?: HttpContext): Observable<Array<Exercise>> {
    return this.apiScheduleTodayExerciseGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Exercise>>): Array<Exercise> => r.body)
    );
  }

  /** Path part for operation `apiScheduleExercisePost()` */
  static readonly ApiScheduleExercisePostPath = '/api/Schedule/exercise';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiScheduleExercisePost()` instead.
   *
   * This method sends a `POST` request.
   */
  apiScheduleExercisePost$Response(params: ApiScheduleExercisePost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkoutLog>> {
    return apiScheduleExercisePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiScheduleExercisePost$Response()` instead.
   *
   * This method sends a `POST` request.
   */
  apiScheduleExercisePost(params: ApiScheduleExercisePost$Params, context?: HttpContext): Observable<WorkoutLog> {
    return this.apiScheduleExercisePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkoutLog>): WorkoutLog => r.body)
    );
  }
  static readonly ApiScheduleMondayGetPath = '/api/Schedule/{monday}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiScheduleMondayGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiScheduleMondayGet$Response(params: ApiScheduleMondayGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WeeklySchedule>>> {
    return apiScheduleMondayGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiScheduleMondayGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiScheduleMondayGet(params: ApiScheduleMondayGet$Params, context?: HttpContext): Observable<Array<WeeklySchedule>> {
    return this.apiScheduleMondayGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<WeeklySchedule>>): Array<WeeklySchedule> => r.body)
    );
  }

  /** Path part for operation `apiSchedulePost()` */
  static readonly ApiSchedulePostPath = '/api/Schedule';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSchedulePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiSchedulePost$Response(params?: ApiSchedulePost$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return apiSchedulePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSchedulePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiSchedulePost(params?: ApiSchedulePost$Params, context?: HttpContext): Observable<boolean> {
    return this.apiSchedulePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
